# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Chris Vizes"
description:	       "Data visualisation and more"
author:              "Chris Meardon" # I removed this from the footer so I think it's not needed

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

 repository: chrisvizes/chrisvizes.github.io